### ISSUE TITLE
Async HTTP requests still start randomly failing

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#135]
After a restart everything works fine. I thought #129 would fix this...

```
[2016-01-22 11:11:58,595] INFO:lrrbot:Command from vorox4: live 
[2016-01-22 11:11:59,586] ERROR:utils:Exception in future
Traceback (most recent call last):
  File "/srv/lrrbot/lrrbot/common/utils.py", line 394, in check_exception
    future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/srv/lrrbot/lrrbot/common/utils.py", line 197, in wrapper
    self.lastreturn[params] = yield from func(*args, **kwargs)
  File "/srv/lrrbot/lrrbot/lrrbot/commands/live.py", line 57, in live
    streams = yield from twitch.get_streams_followed()
  File "/srv/lrrbot/lrrbot/lrrbot/twitch.py", line 156, in get_streams_followed
    data = yield from utils.http_request_coro(url, headers=headers)
  File "/srv/lrrbot/lrrbot/common/utils.py", line 484, in http_request_coro
    raise firstex
  File "/srv/lrrbot/lrrbot/common/utils.py", line 472, in http_request_coro
    raise urllib.error.HTTPError(res.url, res.status, res.reason, res.headers, None)
urllib.error.HTTPError: HTTP Error 413: Request Entity Too Large
[2016-01-22 11:12:01,197] INFO:lrrbot:Command from server (None): current_game(None)
[2016-01-22 11:12:03,879] ERROR:utils:Exception in do_check
Traceback (most recent call last):
  File "/srv/lrrbot/lrrbot/common/utils.py", line 376, in wrapper
    return (yield from func(*args, **kwargs))
  File "/srv/lrrbot/lrrbot/lrrbot/twitchsubs.py", line 26, in do_check
    sublist = yield from twitch.get_subscribers(config['channel'])
  File "/srv/lrrbot/lrrbot/lrrbot/twitch.py", line 95, in get_subscribers
    res = yield from utils.http_request_coro("https://api.twitch.tv/kraken/channels/%s/subscriptions" % channel, headers=headers, data=data)
  File "/srv/lrrbot/lrrbot/common/utils.py", line 484, in http_request_coro
    raise firstex
  File "/srv/lrrbot/lrrbot/common/utils.py", line 472, in http_request_coro
    raise urllib.error.HTTPError(res.url, res.status, res.reason, res.headers, None)
urllib.error.HTTPError: HTTP Error 400: Bad request
```

**Comment by mrphlip** [comment]
So I'm thinking we shouldn't merge #128 until this is fixed...

**Comment by andreasots** [comment]
I think this is an exception safety problem. We should bump the minimum required Python version to 3.5 and use `async with` inside `http_request_coro`. Also if `aiohttp` overflows the stack LRRbot should just `os.abort()`.

**Comment by andreasots** [comment]
```
[2016-02-16 08:43:26,915] INFO:utils:Downloading https://api.twitch.tv/kraken/channels/loadingreadyrun/subscriptions failed: TimeoutError: , retrying...
[2016-02-16 08:44:32,823] INFO:utils:Downloading https://api.twitch.tv/kraken/channels/loadingreadyrun/subscriptions failed: TimeoutError: , retrying...
[2016-02-16 08:44:37,836] INFO:utils:Downloading https://api.twitch.tv/kraken/channels/loadingreadyrun/subscriptions failed: TimeoutError: , retrying...
[2016-02-16 08:44:42,842] ERROR:utils:Exception in do_check
Traceback (most recent call last):
  File "/srv/lrrbot/lrrbot/common/utils.py", line 385, in wrapper
    return (yield from func(*args, **kwargs))
  File "/srv/lrrbot/lrrbot/lrrbot/twitchsubs.py", line 26, in do_check
    sublist = yield from twitch.get_subscribers(config['channel'])
  File "/srv/lrrbot/lrrbot/lrrbot/twitch.py", line 95, in get_subscribers
    res = yield from utils.http_request_coro("https://api.twitch.tv/kraken/channels/%s/subscriptions" % channel, headers=headers, data=data)
  File "/srv/lrrbot/lrrbot/common/utils.py", line 493, in http_request_coro
    raise firstex
  File "/srv/lrrbot/lrrbot/common/utils.py", line 471, in http_request_coro
    res = yield from asyncio.wait_for(http_request_session.request(real_method, url, params=params, data=data, headers=headers, allow_redirects=allow_redirects), timeout)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 382, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

\<incoherent gibberish\>

**Comment by d3fr0st** [comment]
Feel free to shoot me down right away on this one since I understand very little of this... But could this be a problem from the twitch side which might be unrelated to us?

**Comment by andreasots** [comment]
> But could this be a problem from the twitch side which might be unrelated to us?

The errors occurred on every request and went away when the bot was restarted. Even if it was Twitch then we still need to do something about it.

**Comment by mrphlip** [comment]
In case there was any doubt, this is still happening...
```
[2016-07-23 05:06:05,291] INFO:command_parser:Command from admiralmemo: highlight Good Boy 
[2016-07-23 05:06:11,050] INFO:common.http:Downloading https://api.twitch.tv/kraken/channels/loadingreadyrun/videos failed: TimeoutError: , retrying...
[2016-07-23 05:06:16,054] INFO:common.http:Downloading https://api.twitch.tv/kraken/channels/loadingreadyrun/videos failed: TimeoutError: , retrying...
[2016-07-23 05:06:21,058] ERROR:utils:Exception in future
Traceback (most recent call last):
  File "/srv/lrrbot/lrrbot/common/utils.py", line 240, in check_exception
    future.result()
  File "/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/lrrbot/lrrbot/lrrbot/decorators.py", line 74, in wrapper
    return (yield from func(self, conn, event, *args, **kwargs))
  File "/srv/lrrbot/lrrbot/lrrbot/decorators.py", line 51, in wrapper
    return (yield from func(self, conn, event, *args, **kwargs))
  File "/srv/lrrbot/lrrbot/common/utils.py", line 168, in wrapper
    self.lastreturn[params] = yield from func(*args, **kwargs)
  File "/srv/lrrbot/lrrbot/lrrbot/commands/highlights.py", line 32, in highlight
    for video in (yield from twitch.get_videos(broadcasts=True)):
  File "/srv/lrrbot/lrrbot/common/twitch.py", line 183, in get_videos
    "hls": hls,
  File "/srv/lrrbot/lrrbot/common/http.py", line 103, in request_coro
    raise firstex
  File "/srv/lrrbot/lrrbot/common/http.py", line 79, in request_coro
    res = yield from asyncio.wait_for(http_request_session.request(real_method, url, params=params, data=data, headers=headers, allow_redirects=allow_redirects), timeout)
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 396, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

**Comment by andreasots** [comment]
Probably safe to close it now.
