### ISSUE TITLE
Web server throwing a lot of 500s

### ISSUE THREAD

**Issue by mrphlip** [mrphlip/lrrbot#141]
Getting a lot of "500 Internal Server Error" right now... Site is still working intermittently, but is erroring more often than it works...

**Comment by andreasots** [comment]
```
Exception on /api/stats/death [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/api.py", line 8, in api_stats
    game_id = botinteract.get_current_game()
  File "./www/botinteract.py", line 28, in get_current_game
    return send_bot_command("current_game", None)
  File "./www/login.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "./www/botinteract.py", line 24, in send_bot_command
    buf += conn.recv(1024)
socket.timeout: timed out
[pid: 1477|app: 0|req: 291/796] █████████████████ () {42 vars in 763 bytes} [Tue Feb  9 16:21:20 2016] GET /api/stats/death => generated 291 bytes in 5016 msecs (HTTP/1.1 500) 2 headers in 84 bytes (2 switches on core 0)
```

**Comment by andreasots** [comment]
The bot is refetching https://api.twitch.tv/kraken/chat/emoticons every ten seconds.

**Comment by mrphlip** [comment]
Well, e3ff1e3261735925832c5e6bc024d2f676038dc9 should help there, we'll see if that clears everything up, or if there's still problems...

**Comment by andreasots** [comment]
Seems fixed.

**Comment by AdmiralMemo** [comment]
It's doing it again. Been doing it for about a week.
