### ISSUE TITLE
Whispers disabled because Twitch is a butt

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#148]
```
$ python3 start_bot.py
Traceback (most recent call last):
  File "start_bot.py", line 5, in <module>
    from lrrbot.main import bot, log
  File "/srv/lrrbot/lrrbot/lrrbot/main.py", line 534, in <module>
    bot = LRRBot(asyncio.get_event_loop())
  File "/srv/lrrbot/lrrbot/lrrbot/main.py", line 55, in __init__
    self.whisperconn = whisper.TwitchWhisper(self.loop, self.service)
  File "/srv/lrrbot/lrrbot/lrrbot/whisper.py", line 18, in __init__
    ) for host, port in twitch.get_group_servers()]
  File "/srv/lrrbot/lrrbot/lrrbot/twitch.py", line 120, in get_group_servers
    res = common.http.request("https://chatdepot.twitch.tv/room_memberships", {'oauth_token': storage.data['twitch_oauth'][config['username']]}, maxtries=1)
  File "/srv/lrrbot/lrrbot/common/http.py", line 54, in request
    raise firstex
  File "/srv/lrrbot/lrrbot/common/http.py", line 45, in request
    return urllib.request.urlopen(req, timeout=timeout).read().decode("utf-8")
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 470, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 580, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 508, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 588, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

```
$ curl -v https://chatdepot.twitch.tv/room_memberships?oauth_token=██████████████████████████████
*   Trying 192.16.64.138...
* Connected to chatdepot.twitch.tv (192.16.64.138) port 443 (#0)
* found 175 certificates in /etc/ssl/certs/ca-certificates.crt
* found 704 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: *.twitch.tv (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: C=US,ST=California,L=San Francisco,O=Twitch Interactive\, Inc.,CN=*.twitch.tv
*        start date: Fri, 06 Mar 2015 00:00:00 GMT
*        expire date: Wed, 14 Mar 2018 12:00:00 GMT
*        issuer: C=US,O=DigiCert Inc,CN=DigiCert SHA2 Secure Server CA
*        compression: NULL
* ALPN, server did not agree to a protocol
> GET /room_memberships?oauth_token=██████████████████████████████ HTTP/1.1
> Host: chatdepot.twitch.tv
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Server: nginx
< Date: Wed, 02 Mar 2016 07:08:45 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 59
< Connection: close
< 
* Closing connection 0
{"code":"unknown","message":"Unexpected error","errors":[]}
```

**Comment by andreasots** [comment]
Whispers are now working.
