### ISSUE TITLE
Repeated error all night

### ISSUE THREAD

**Issue by d3fr0st** [mrphlip/lrrbot#156]
```python-traceback
 ERROR:utils:Exception in do_check
Traceback (most recent call last):
  File "/srv/lrrbot/lrrbot/common/utils.py", line 217, in wrapper
    return (yield from func(*args, **kwargs))
  File "/srv/lrrbot/lrrbot/lrrbot/twitchsubs.py", line 26, in do_check
    sublist = yield from twitch.get_subscribers(config['channel'])
  File "/srv/lrrbot/lrrbot/lrrbot/twitch.py", line 109, in get_subscribers
    res = yield from common.http.request_coro("https://api.twitch.tv/kraken/channels/%s/subscriptions" % channel, headers=headers, data=data)
  File "/srv/lrrbot/lrrbot/common/http.py", line 98, in request_coro
    raise firstex
  File "/srv/lrrbot/lrrbot/common/http.py", line 76, in request_coro
    res = yield from asyncio.wait_for(http_request_session.request(real_method, url, params=params, data=data, headers=headers, allow_redirects=allow_redirects), timeout)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 382, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

first incident [2016-03-10 03:13:03,734], stops !highlight from working... probably some other stuff too :/

**Comment by andreasots** [comment]
Looks like #135.

**Comment by d3fr0st** [comment]
it seems to persist through reboots now though... Also stop stuff like !highlight to work completely

**Comment by andreasots** [comment]
From the log I see that the last HTTP request that failed was at 2016-03-10 06:06:52,340 and that's before the bot was restarted at 2016-03-10 06:07:14,854. The restart before that was at 2016-03-07 22:46:55,628. So it's not persisting through reboots.

**Comment by d3fr0st** [comment]
Uh I'm not used to the new restart... I guess I tried my test before the bot actually restarted. I'll give it more time in the future. Also yeah I'll close this since we already got #135
