### ISSUE TITLE
/stats: sqlalchemy.exc.ResourceClosedError: This result object does not return rows. It has been closed automatically.

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#188]
```python-traceback
Exception on /stats [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./common/utils.py", line 100, in decorated_func
    next(x)
  File "./www/login.py", line 58, in wrapper
    kwargs['session'] = load_session()
  File "./www/login.py", line 184, in load_session
    ]).where(game_votes.c.game_id == game_id).where(game_votes.c.show_id == show_id)).first()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/result.py", line 1038, in first
    return self._non_result(None)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/result.py", line 920, in _non_result
    "This result object does not return rows. "
sqlalchemy.exc.ResourceClosedError: This result object does not return rows. It has been closed automatically.
```

**Comment by andreasots** [comment]
I think this might have been caused by having Postgres connections shared between processes. It should be fixed now. Will keep monitoring the logs.

**Comment by andreasots** [comment]
It seems gone now.
