### ISSUE TITLE
TypeError: a float is required

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#200]
```
mai   05 08:54:57 qrpth.eu env[28683]: [2016-05-05 08:54:57,841] ERROR:utils:Exception in vote_respond
mai   05 08:54:57 qrpth.eu env[28683]: Traceback (most recent call last):
mai   05 08:54:57 qrpth.eu env[28683]:   File "/srv/lrrbot/lrrbot/common/utils.py", line 222, in wrapper
mai   05 08:54:57 qrpth.eu env[28683]:     return (yield from func(*args, **kwargs))
mai   05 08:54:57 qrpth.eu env[28683]:   File "/usr/lib64/python3.5/asyncio/coroutines.py", line 206, in coro
mai   05 08:54:57 qrpth.eu env[28683]:     res = func(*args, **kw)
mai   05 08:54:57 qrpth.eu env[28683]:   File "/srv/lrrbot/lrrbot/lrrbot/main.py", line 413, in vote_respond
mai   05 08:54:57 qrpth.eu env[28683]:     vote_respond(self, self.connection, *self.vote_update)
mai   05 08:54:57 qrpth.eu env[28683]:   File "/srv/lrrbot/lrrbot/common/utils.py", line 100, in decorated_func
mai   05 08:54:57 qrpth.eu env[28683]:     next(x)
mai   05 08:54:57 qrpth.eu env[28683]:   File "/srv/lrrbot/lrrbot/common/utils.py", line 168, in wrapper
mai   05 08:54:57 qrpth.eu env[28683]:     self.lastreturn[params] = yield from func(*args, **kwargs)
mai   05 08:54:57 qrpth.eu env[28683]:   File "/usr/lib64/python3.5/asyncio/coroutines.py", line 206, in coro
mai   05 08:54:57 qrpth.eu env[28683]:     res = func(*args, **kw)
mai   05 08:54:57 qrpth.eu env[28683]:   File "/srv/lrrbot/lrrbot/lrrbot/commands/game.py", line 112, in vote_respond
mai   05 08:54:57 qrpth.eu env[28683]:     conn.privmsg(respond_to, "Rating for %s on %s is now %0.0f%% (%d/%d)" % (game, show, rating, good, total))
mai   05 08:54:57 qrpth.eu env[28683]: TypeError: a float is required
```

This error gets emitted every five seconds.

**Comment by andreasots** [comment]
Fixed already by #265 by removing that code.
