### ISSUE TITLE
lrrbot.rpc.get_tweet: ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#211]
```
juuni 02 13:00:05 qrpth.eu env[25175]: /usr/lib64/python3.5/site-packages/sqlalchemy/sql/elements.py:3871: SAWarning: Textual column expression 'shows' should be explicitly declared with text('shows'), or use column('shows') for more specificity (this warning may be suppressed after 10 occurrences)
juuni 02 13:00:05 qrpth.eu env[25175]:   if guess_is_literal else "column"
juuni 02 13:00:05 qrpth.eu env[25175]: [2016-06-02 13:00:05,417] ERROR:serverevents:Exception in on_server_event
juuni 02 13:00:05 qrpth.eu env[25175]: Traceback (most recent call last):
juuni 02 13:00:05 qrpth.eu env[25175]:   File "/srv/lrrbot/lrrbot/lrrbot/rpc.py", line 70, in data_received
juuni 02 13:00:05 qrpth.eu env[25175]:     response = self.server.functions[request['command']](self.server.lrrbot, request['user'], request['param'])
juuni 02 13:00:05 qrpth.eu env[25175]:   File "/srv/lrrbot/lrrbot/lrrbot/rpc.py", line 220, in get_tweet
juuni 02 13:00:05 qrpth.eu env[25175]:     ), 1)[0]
juuni 02 13:00:05 qrpth.eu env[25175]:   File "/srv/lrrbot/lrrbot/common/utils.py", line 328, in pick_weighted_random_elements
juuni 02 13:00:05 qrpth.eu env[25175]:     r = random.random() ** (1 / weight)
juuni 02 13:00:05 qrpth.eu env[25175]: ZeroDivisionError: float division by zero
juuni 02 13:00:05 qrpth.eu uwsgi[1480]: Exception on /api/tweet [GET]
juuni 02 13:00:05 qrpth.eu uwsgi[1480]: Traceback (most recent call last):
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:   File "/usr/lib64/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:     response = self.full_dispatch_request()
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:   File "/usr/lib64/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:     rv = self.handle_user_exception(e)
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:   File "/usr/lib64/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:     reraise(exc_type, exc_value, tb)
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:   File "/usr/lib64/python3.5/site-packages/flask/_compat.py", line 33, in reraise
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:     raise value
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:   File "/usr/lib64/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:     rv = self.dispatch_request()
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:   File "/usr/lib64/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:     return self.view_functions[rule.endpoint](**req.view_args)
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:   File "./common/utils.py", line 100, in decorated_func
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:     next(x)
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:   File "./www/login.py", line 80, in wrapper
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:     return (yield from func(*args, **kwargs))
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:   File "/usr/lib64/python3.5/asyncio/coroutines.py", line 206, in coro
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:     res = func(*args, **kw)
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:   File "./www/api.py", line 103, in get_tweet
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:     tweet = botinteract.get_tweet()
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:   File "./www/botinteract.py", line 93, in get_tweet
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:     return send_bot_command("get_tweet", None)
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:   File "./common/utils.py", line 100, in decorated_func
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:     next(x)
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:   File "./www/login.py", line 80, in wrapper
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:     return (yield from func(*args, **kwargs))
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:   File "/usr/lib64/python3.5/asyncio/coroutines.py", line 206, in coro
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:     res = func(*args, **kw)
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:   File "./www/botinteract.py", line 35, in send_bot_command
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:     raise APIError("Server error in %s:\n%s" % (command, result['result']))
juuni 02 13:00:05 qrpth.eu uwsgi[1480]: www.botinteract.APIError: Server error in get_tweet:
juuni 02 13:00:05 qrpth.eu uwsgi[1480]: Traceback (most recent call last):
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:   File "/srv/lrrbot/lrrbot/lrrbot/rpc.py", line 70, in data_received
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:     response = self.server.functions[request['command']](self.server.lrrbot, request['user'], request['param'])
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:   File "/srv/lrrbot/lrrbot/lrrbot/rpc.py", line 220, in get_tweet
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:     ), 1)[0]
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:   File "/srv/lrrbot/lrrbot/common/utils.py", line 328, in pick_weighted_random_elements
juuni 02 13:00:05 qrpth.eu uwsgi[1480]:     r = random.random() ** (1 / weight)
juuni 02 13:00:05 qrpth.eu uwsgi[1480]: ZeroDivisionError: float division by zero
juuni 02 13:00:05 qrpth.eu uwsgi[1480]: 
juuni 02 13:00:05 qrpth.eu uwsgi[1480]: [pid: 1481|app: 0|req: 672/4114] 121.44.27.152 () {34 vars in 446 bytes} [Thu Jun  2 13:00:05 2016] GET /api/tweet?apipass=PKvW9q1E3MTCU2a3 => generated 291 bytes in 459 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
```

**Comment by andreasots** [comment]
Well lrrEFF. Changing the `apipass`.
