### ISSUE TITLE
New re-subs aren't working

### ISSUE THREAD

**Issue by mrphlip** [mrphlip/lrrbot#215]
The [new resubs](https://discuss.dev.twitch.tv/t/important-re-subscription-change/6463) don't seem to be working properly, lrrbot is just ignoring them.

They were working during Checkpoint+ but stopped working for Matters of Import, I guess that's when they rolled out the changes.

**Comment by mrphlip** [comment]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib64/python3.5/site-packages/irc/client.py", line 216, in process_data
    c.process_data()
  File "/usr/lib64/python3.5/site-packages/irc/client.py", line 582, in process_data
    self._process_line(line)
  File "/usr/lib64/python3.5/site-packages/irc/client.py", line 614, in _process_line
    handler(arguments, command, source, tags)
  File "/usr/lib64/python3.5/site-packages/irc/client.py", line 663, in _handle_other
    self._handle_event(event)
  File "/usr/lib64/python3.5/site-packages/irc/client.py", line 673, in _handle_event
    self.reactor._handle_event(self, event)
  File "/usr/lib64/python3.5/site-packages/irc/client.py", line 398, in _handle_event
    result = handler.callback(connection, event)
  File "/srv/lrrbot/lrrbot/lrrbot/twitchsubs.py", line 117, in on_usernotice
    asyncio.ensure_future(self.on_subscriber(conn, "#" + config['channel'], tag['display-name'], datetime.datetime.now(tz=pytz.utc), monthcount=tags.get('msg-param-months'), message=message)).add_done_callback(utils.check_exception)
NameError: name 'tag' is not defined
```

**Comment by andreasots** [comment]
Should be fixed now.
