### ISSUE TITLE
AttributeError: 'str' object has no attribute 'isoformat'

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#217]
```
juuni 21 05:36:42 qrpth.eu env[7262]: [2016-06-21 05:36:42,300] INFO:twitchsubs:Notification: PleaseAnswerTheEffingTree just subscribed!
juuni 21 05:37:29 qrpth.eu env[7262]: [2016-06-21 05:37:29,899] INFO:twitchsubs:Found new subscriber via Twitch API: PleaseAnswerTheEffingTree
juuni 21 05:38:31 qrpth.eu env[7262]: [2016-06-21 05:38:31,425] ERROR:utils:Exception in future
juuni 21 05:38:31 qrpth.eu env[7262]: Traceback (most recent call last):
juuni 21 05:38:31 qrpth.eu env[7262]:   File "/srv/lrrbot/lrrbot/common/utils.py", line 240, in check_exception
juuni 21 05:38:31 qrpth.eu env[7262]:     future.result()
juuni 21 05:38:31 qrpth.eu env[7262]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
juuni 21 05:38:31 qrpth.eu env[7262]:     raise self._exception
juuni 21 05:38:31 qrpth.eu env[7262]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 241, in _step
juuni 21 05:38:31 qrpth.eu env[7262]:     result = coro.throw(exc)
juuni 21 05:38:31 qrpth.eu env[7262]:   File "/srv/lrrbot/lrrbot/lrrbot/twitchsubs.py", line 163, in on_subscriber
juuni 21 05:38:31 qrpth.eu env[7262]:     await common.rpc.eventserver.event(event, data, eventtime)
juuni 21 05:38:31 qrpth.eu env[7262]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 358, in __iter__
juuni 21 05:38:31 qrpth.eu env[7262]:     yield self  # This tells Task to wait for completion.
juuni 21 05:38:31 qrpth.eu env[7262]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 290, in _wakeup
juuni 21 05:38:31 qrpth.eu env[7262]:     future.result()
juuni 21 05:38:31 qrpth.eu env[7262]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
juuni 21 05:38:31 qrpth.eu env[7262]:     raise self._exception
juuni 21 05:38:31 qrpth.eu env[7262]: aiomas.exceptions.RemoteException: Origin: /tmp/eventserver.sock
juuni 21 05:38:31 qrpth.eu env[7262]: Traceback (most recent call last):
juuni 21 05:38:31 qrpth.eu env[7262]:   File "/usr/lib64/python3.5/site-packages/aiomas/rpc.py", line 161, in _handle_request
juuni 21 05:38:31 qrpth.eu env[7262]:     res = yield from asyncio.async(res, loop=loop)
juuni 21 05:38:31 qrpth.eu env[7262]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 358, in __iter__
juuni 21 05:38:31 qrpth.eu env[7262]:     yield self  # This tells Task to wait for completion.
juuni 21 05:38:31 qrpth.eu env[7262]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 290, in _wakeup
juuni 21 05:38:31 qrpth.eu env[7262]:     future.result()
juuni 21 05:38:31 qrpth.eu env[7262]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
juuni 21 05:38:31 qrpth.eu env[7262]:     raise self._exception
juuni 21 05:38:31 qrpth.eu env[7262]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 239, in _step
juuni 21 05:38:31 qrpth.eu env[7262]:     result = coro.send(None)
juuni 21 05:38:31 qrpth.eu env[7262]:   File "/srv/lrrbot/lrrbot/eventserver.py", line 114, in event
juuni 21 05:38:31 qrpth.eu env[7262]:     'data': dict(data, time=time.isoformat()),
juuni 21 05:38:31 qrpth.eu env[7262]: AttributeError: 'str' object has no attribute 'isoformat'
```
Some kind of scope error?

**Comment by d3fr0st** [comment]
So it looks like this is causing the bot to go down fairly frequently

**Comment by andreasots** [comment]
It seems fbf2b90 fixed it.
