### ISSUE TITLE
Resub: AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#218]
```
`Jun 21 22:01:42 qrpth.eu env[8728]: [2016-06-21 22:01:42,626] ERROR:utils:Exception in future
Jun 21 22:01:42 qrpth.eu env[8728]: Traceback (most recent call last):
Jun 21 22:01:42 qrpth.eu env[8728]:   File "/srv/lrrbot/lrrbot/common/utils.py", line 240, in check_exception
Jun 21 22:01:42 qrpth.eu env[8728]:     future.result()
Jun 21 22:01:42 qrpth.eu env[8728]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
Jun 21 22:01:42 qrpth.eu env[8728]:     raise self._exception
Jun 21 22:01:42 qrpth.eu env[8728]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 239, in _step
Jun 21 22:01:42 qrpth.eu env[8728]:     result = coro.send(None)
Jun 21 22:01:42 qrpth.eu env[8728]:   File "/srv/lrrbot/lrrbot/lrrbot/twitchsubs.py", line 125, in on_subscriber
Jun 21 22:01:42 qrpth.eu env[8728]:     if user.lower() in self.last_announced_subs:
Jun 21 22:01:42 qrpth.eu env[8728]: AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by mrphlip** [comment]
This is still occurring...
```
[2016-06-28 06:26:25,944] ERROR:utils:Exception in future
Traceback (most recent call last):
  File "/srv/lrrbot/lrrbot/common/utils.py", line 240, in check_exception
    future.result()
  File "/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/lrrbot/lrrbot/lrrbot/twitchsubs.py", line 124, in on_subscriber
    if user.lower() in self.last_announced_subs:
AttributeError: 'NoneType' object has no attribute 'lower'
```
