### ISSUE TITLE
Setup instructions data.json file

### ISSUE THREAD

**Issue by danieljcrabtree** [mrphlip/lrrbot#244]
I'm trying to install lrrbot because I was going to offer to try to squash a few bugs for you but I'm having trouble setting it up.

Running `alembic` with the `data.json` template file in the instructions causes `start_bot.py` to throw an exception:

```
Traceback (most recent call last):
  File "start_bot.py", line 8, in <module>
    from lrrbot.main import bot, log
  File "/vagrant/lrrbot/lrrbot/main.py", line 472, in <module>
    bot = LRRBot(asyncio.get_event_loop())
  File "/vagrant/lrrbot/lrrbot/main.py", line 132, in __init__
    self.moderator_actions = moderator_actions.ModeratorActions(self, loop)
  File "/vagrant/lrrbot/lrrbot/moderator_actions.py", line 20, in __init__
    channel_id, = conn.execute(sqlalchemy.select([users.c.id]).where(users.c.name == config['channel'])).first()
TypeError: 'NoneType' object is not iterable
```

It seems to expect that the users table is already populated. Am I missing something?

**Comment by andreasots** [comment]
Thanks!

This should now be fixed.

**Comment by danieljcrabtree** [comment]
Thanks!
