### ISSUE TITLE
common.pubsub: websocket closed and not reopened

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#253]
```
[2016-12-08 10:07:04,566] ERROR:utils:Exception in future
Traceback (most recent call last):
  File "/srv/lrrbot/lrrbot/common/utils.py", line 243, in check_exception
    future.result()
  File "/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/lrrbot/lrrbot/common/pubsub.py", line 114, in _ping
    'type': 'PING',
  File "/usr/lib64/python3.5/site-packages/aiohttp/client_ws.py", line 74, in send_json
    self.send_str(dumps(data))
  File "/usr/lib64/python3.5/site-packages/aiohttp/client_ws.py", line 60, in send_str
    raise RuntimeError('websocket connection is closed')
RuntimeError: websocket connection is closed
```

**Comment by mrphlip** [comment]
Possibly related?
```
[2018-02-27 01:27:31,760] ERROR:common.pubsub:Exception in PubSub message task
Traceback (most recent call last):
  File "/srv/lrrbot/lrrbot/venv/lib/python3.5/site-packages/aiohttp/client_ws.py", line 194, in receive
    msg = await self._reader.read()
  File "/srv/lrrbot/lrrbot/venv/lib/python3.5/site-packages/aiohttp/streams.py", line 571, in read
    return await super().read()
  File "/srv/lrrbot/lrrbot/venv/lib/python3.5/site-packages/aiohttp/streams.py", line 546, in read
    raise EofStream
aiohttp.streams.EofStream

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/lrrbot/lrrbot/common/pubsub.py", line 167, in message_pump
    raise Exception("Error reading message") from pubsub.exception()
Exception: Error reading message
```

**Comment by mrphlip** [comment]
OK, so the original bug hasn't happened in forever, so it's probably fixed???

The newer bug was another aiohttp 3.0.0 breakage, `send_json` is async now. Is now fixed.
