### ISSUE TITLE
Error linking to Patreon

### ISSUE THREAD

**Issue by mrphlip** [mrphlip/lrrbot#427]
User is getting this when trying to load `/patreon/` after attempting to link their Patreon account:
```
[2018-01-13 06:48:42,613] ERROR in app: Exception on /patreon/ [GET]
Traceback (most recent call last):
  File "/srv/lrrbot/lrrbot/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/lrrbot/lrrbot/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/lrrbot/lrrbot/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/lrrbot/lrrbot/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/lrrbot/lrrbot/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/lrrbot/lrrbot/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./www/server.py", line 24, in inner
    return asyncio.get_event_loop().run_until_complete(view_func(*args, **kwargs))
  File "/usr/lib64/python3.5/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "./www/login.py", line 79, in wrapper
    return await asyncio.coroutine(func)(*args, **kwargs)
  File "./www/patreon.py", line 47, in patreon_index
    token = await patreon.get_token(server.db.engine, server.db.metadata, session['user']['id'])
  File "./common/patreon.py", line 42, in get_token
    raise Exception("User not logged in")
Exception: User not logged in
```
Looking through the code, to get to here you'd need to have `session['user']['patreon_user_id'] is not None` but the query to get the `patreon_users` row returned no results... but there don't seem to be any rows in the database where that's true? And it shouldn't anyway, since it's a foreign key, which is supposed to enforce that sort of thing?

I'm still talking to the user, getting their Twitch username so I can look at their row in specific, see if there's anything odd with it...

**Comment by mrphlip** [comment]
Oops, I said a magic word in the commit. Leaving this open until it's confirmed if this actually fixes it for the user...

**Comment by mrphlip** [comment]
This hasn't happened since, so looks like the fix worked.
