### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by andreasots** [mrphlip/lrrbot#97]
```
[2015-06-14 23:06:39,163] INFO:lrrbot:Bot shutdown
Traceback (most recent call last):
  File "start_bot.py", line 24, in <module>
    bot.start()
  File "/srv/lrrbot/lrrbot/lrrbot/__init__.py", line 125, in start
    self.reactor.process_data(i)
  File "/usr/local/lib/python3.4/dist-packages/irc/client.py", line 214, in process_data
    c.process_data()
  File "/usr/local/lib/python3.4/dist-packages/irc/client.py", line 583, in process_data
    self._process_line(line)
  File "/usr/local/lib/python3.4/dist-packages/irc/client.py", line 673, in _process_line
    target = arguments[0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by andreasots** [comment]
It might be worth running LRRbot as a systemd user service so when it crashes it's automatically restarted.

**Comment by mrphlip** [comment]
I'm guessing it's something new with one of the new Twitch-specific commands. Looking at the code, it'll happen whenever there's a message that doesn't have any arguments, because the code seems to be assuming on faith that there'll always be at least one argument, and the first arg is the target of the message.

And... looking at the Twitch doc, it looks like that's the case for all of the Twitch addon commands too, except for `GLOBALUSERSTATE`, which is undocumented, but probably (given "global" is in the name) doesn't have a target.

I can't tell if that's what caused this, though, there's no details in the log. If this keeps happening, I'll turn on more detailed logging so we can try to track it down.

On the other side... yeah, turning this into a proper service would make some amount of sense... `screen` is a useful piece of software, but an effective service manager it isn't.
